version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./photos:/app/photos
    ports:
      - "8000:8000"

  postgres:
    image: postgres:13
    container_name: postgres13
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pas123'
      POSTGRES_DB: 'auction'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: