version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres13
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pas123'
      POSTGRES_DB: 'auction'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: