DEBUG_MODE = False
MINUTES_TO_ENLARGE = 1 if DEBUG_MODE else 2
TIME_FOR_AUTO_BIDS = 2 if DEBUG_MODE else 6
ADDITIONAL_MINUTES = 1 if DEBUG_MODE else 5
AUCTION_LENGTH_MINUTES = 3 if DEBUG_MODE else 30
